// SPDX-License-Identifier: MIT
// ============================================================================
// ZeroID — On-Chain Groth16 Verifier + Gate Contract
// © thesecretlab | "Verify the human. Drop the liability."
// ============================================================================
pragma solidity ^0.8.20;

/**
 * @title Pairing
 * @dev BN254 elliptic curve pairing operations for Groth16 verification.
 */
library Pairing {
    struct G1Point {
        uint256 X;
        uint256 Y;
    }

    struct G2Point {
        uint256[2] X;
        uint256[2] Y;
    }

    /// @dev Returns the generator of G1.
    function P1() internal pure returns (G1Point memory) {
        return G1Point(1, 2);
    }

    /// @dev Returns the generator of G2.
    function P2() internal pure returns (G2Point memory) {
        return G2Point(
            [
                11559732032986387107991004021392285783925812861821192530917403151452391805634,
                10857046999023057135944570762232829481370756359578518086990519993285655852781
            ],
            [
                4082367875863433681332203403145435568316851327593401208105741076214120093531,
                8495653923123431417604973247489272438418190587263600148770280649306958101930
            ]
        );
    }

    /// @dev Returns the negation of p, i.e., p.addition(p.negate()) should be zero.
    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        uint256 q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
        return G1Point(p.X, q - (p.Y % q));
    }

    /// @dev Returns the sum of two G1 points using the precompiled contract at address 6.
    function addition(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
        uint256[4] memory input;
        input[0] = p1.X;
        input[1] = p1.Y;
        input[2] = p2.X;
        input[3] = p2.Y;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 6, input, 0xc0, r, 0x60)
        }
        require(success, "pairing-add-failed");
    }

    /// @dev Returns the product of a G1 point and a scalar using precompiled contract at address 7.
    function scalar_mul(G1Point memory p, uint256 s) internal view returns (G1Point memory r) {
        uint256[3] memory input;
        input[0] = p.X;
        input[1] = p.Y;
        input[2] = s;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 7, input, 0x60, r, 0x60)
        }
        require(success, "pairing-mul-failed");
    }

    /// @dev Performs a pairing check: e(p1[0], p2[0]) * ... * e(p1[n], p2[n]) == 1
    function pairing(G1Point[] memory p1, G2Point[] memory p2) internal view returns (bool) {
        require(p1.length == p2.length, "pairing-lengths-mismatch");
        uint256 elements = p1.length;
        uint256 inputSize = elements * 6;
        uint256[] memory input = new uint256[](inputSize);
        for (uint256 i = 0; i < elements; i++) {
            input[i * 6 + 0] = p1[i].X;
            input[i * 6 + 1] = p1[i].Y;
            input[i * 6 + 2] = p2[i].X[0];
            input[i * 6 + 3] = p2[i].X[1];
            input[i * 6 + 4] = p2[i].Y[0];
            input[i * 6 + 5] = p2[i].Y[1];
        }
        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 8, add(input, 0x20), mul(inputSize, 0x20), out, 0x20)
        }
        require(success, "pairing-opcode-failed");
        return out[0] != 0;
    }

    /// @dev Convenience method for 4-point pairing check.
    function pairingProd4(
        G1Point memory a1, G2Point memory a2,
        G1Point memory b1, G2Point memory b2,
        G1Point memory c1, G2Point memory c2,
        G1Point memory d1, G2Point memory d2
    ) internal view returns (bool) {
        G1Point[] memory p1 = new G1Point[](4);
        G2Point[] memory p2 = new G2Point[](4);
        p1[0] = a1; p2[0] = a2;
        p1[1] = b1; p2[1] = b2;
        p1[2] = c1; p2[2] = c2;
        p1[3] = d1; p2[3] = d2;
        return pairing(p1, p2);
    }
}

/**
 * @title Groth16Verifier
 * @dev Verifies Groth16 proofs for the ZeroID KYC circuit.
 * @notice Verification key values are placeholders — replace with actual
 *         values generated by `snarkjs zkey export solidityverifier`.
 */
contract Groth16Verifier {
    using Pairing for *;

    // Number of public inputs (issuerPubKey[2], requiredAge, restrictedCountryCode, appId, nullifier, credentialHash)
    uint256 constant PUBLIC_INPUTS = 7;

    struct VerifyingKey {
        Pairing.G1Point alfa1;
        Pairing.G2Point beta2;
        Pairing.G2Point gamma2;
        Pairing.G2Point delta2;
        Pairing.G1Point[] IC;
    }

    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    function verifyingKey() internal pure returns (VerifyingKey memory vk) {
        // NOTE: These are placeholder values. After running the trusted setup,
        // replace with the actual verification key from verification_key.json.
        vk.alfa1 = Pairing.G1Point(
            20491192805390485299153009773594534940189261866228447918068658471970481763042,
            9383485363053290200918347156157836566562967994039712273449902621266178545958
        );
        vk.beta2 = Pairing.G2Point(
            [4252822878758300859123897981450591353533073413197771768651442665752259397132,
             6375614351688725206403948262868962793625744043794305715222011528459656738731],
            [21847035105528745403288232691147584728191162732299865338377159692350059136679,
             10505242626370262277552901082094356697409835680220590971873171140371331206856]
        );
        vk.gamma2 = Pairing.G2Point(
            [11559732032986387107991004021392285783925812861821192530917403151452391805634,
             10857046999023057135944570762232829481370756359578518086990519993285655852781],
            [4082367875863433681332203403145435568316851327593401208105741076214120093531,
             8495653923123431417604973247489272438418190587263600148770280649306958101930]
        );
        vk.delta2 = Pairing.G2Point(
            [11559732032986387107991004021392285783925812861821192530917403151452391805634,
             10857046999023057135944570762232829481370756359578518086990519993285655852781],
            [4082367875863433681332203403145435568316851327593401208105741076214120093531,
             8495653923123431417604973247489272438418190587263600148770280649306958101930]
        );
        vk.IC = new Pairing.G1Point[](PUBLIC_INPUTS + 1);
        for (uint256 i = 0; i <= PUBLIC_INPUTS; i++) {
            vk.IC[i] = Pairing.G1Point(1, 2); // Placeholder — replace after setup
        }
    }

    function verify(uint256[] memory input, Proof memory proof) internal view returns (bool) {
        require(input.length == PUBLIC_INPUTS, "verifier-bad-input");
        VerifyingKey memory vk = verifyingKey();

        // Compute the linear combination vk_x
        Pairing.G1Point memory vk_x = Pairing.G1Point(0, 0);
        for (uint256 i = 0; i < input.length; i++) {
            vk_x = Pairing.addition(vk_x, Pairing.scalar_mul(vk.IC[i + 1], input[i]));
        }
        vk_x = Pairing.addition(vk_x, vk.IC[0]);

        return Pairing.pairingProd4(
            Pairing.negate(proof.A), proof.B,
            vk.alfa1, vk.beta2,
            vk_x, vk.gamma2,
            proof.C, vk.delta2
        );
    }

    /// @dev Verifies a Groth16 proof with the given public signals.
    /// @param a The proof point A (G1).
    /// @param b The proof point B (G2).
    /// @param c The proof point C (G1).
    /// @param input The public input signals.
    /// @return r True if the proof is valid.
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[] memory input
    ) public view returns (bool r) {
        Proof memory proof;
        proof.A = Pairing.G1Point(a[0], a[1]);
        proof.B = Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]);
        proof.C = Pairing.G1Point(c[0], c[1]);
        return verify(input, proof);
    }
}

/**
 * @title ZeroIdGate
 * @dev Wrapper contract that verifies ZK proofs and manages verified identities.
 *      Prevents replay attacks via nullifier tracking.
 */
contract ZeroIdGate {
    Groth16Verifier public immutable verifier;

    /// @dev Maps nullifier hashes to their verification status.
    mapping(uint256 => bool) public verifiedNullifiers;

    /// @dev Maps smart account address to its bound nullifier (ERC-4337 integration).
    mapping(address => uint256) public boundNullifiers;

    /// @dev Total number of verified identities.
    uint256 public verifiedCount;

    event IdentityVerified(
        address indexed user,
        uint256 indexed nullifier,
        uint256 credentialHash,
        uint256 timestamp
    );

    event CredentialBound(
        address indexed smartAccount,
        uint256 indexed nullifier,
        uint256 timestamp
    );

    event VerificationFailed(
        address indexed user,
        string reason
    );

    error NullifierAlreadyUsed(uint256 nullifier);
    error InvalidProof();

    constructor(address _verifier) {
        verifier = Groth16Verifier(_verifier);
    }

    /**
     * @dev Verifies a ZK proof and grants verified status.
     * @param a Proof point A.
     * @param b Proof point B.
     * @param c Proof point C.
     * @param publicSignals Array of public signals:
     *   [0-1] issuerPubKey[2]
     *   [2]   requiredAge
     *   [3]   restrictedCountryCode
     *   [4]   appId
     *   [5]   nullifier
     *   [6]   credentialHash
     */
    function verifyAndGrant(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[] memory publicSignals
    ) external returns (bool) {
        require(publicSignals.length == 7, "ZeroIdGate: invalid signal count");

        uint256 nullifier = publicSignals[5];

        // Check nullifier hasn't been used (prevent replay / sybil)
        if (verifiedNullifiers[nullifier]) {
            revert NullifierAlreadyUsed(nullifier);
        }

        // Verify the Groth16 proof
        bool valid = verifier.verifyProof(a, b, c, publicSignals);
        if (!valid) {
            emit VerificationFailed(msg.sender, "Invalid ZK proof");
            revert InvalidProof();
        }

        // Mark nullifier as used
        verifiedNullifiers[nullifier] = true;
        verifiedCount++;

        uint256 credentialHash = publicSignals[6];
        emit IdentityVerified(msg.sender, nullifier, credentialHash, block.timestamp);

        return true;
    }

    /**
     * @dev Check if a nullifier has already been verified.
     */
    function isNullifierUsed(uint256 nullifier) external view returns (bool) {
        return verifiedNullifiers[nullifier];
    }

    /**
     * @dev Bind a verified nullifier to an ERC-4337 smart account address.
     *      Once bound, the smart account can prove "my owner is verified" on-chain.
     *      The nullifier was already verified via verifyAndGrant.
     */
    function bindToSmartAccount(
        address smartAccount,
        uint256 nullifier
    ) external {
        require(verifiedNullifiers[nullifier], "ZeroIdGate: nullifier not verified");
        require(boundNullifiers[smartAccount] == 0, "ZeroIdGate: account already bound");
        require(smartAccount != address(0), "ZeroIdGate: zero address");

        boundNullifiers[smartAccount] = nullifier;
        emit CredentialBound(smartAccount, nullifier, block.timestamp);
    }

    /**
     * @dev Check if a smart account has a bound verified identity.
     *      Used by dApps / paymasters to gate access.
     */
    function isAccountVerified(address smartAccount) external view returns (bool) {
        return boundNullifiers[smartAccount] != 0;
    }
}
